server:
  port: 3000
spring:
  application:
    name: CS-3.0.0
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    username:
    password:
    url: jdbc:h2:~/csdb
